#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ directories }}"
- name: Generate .env
  template:
    src: app.env.j2
    dest: /opt/app/.env